# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 675cec8c5e3eff7ef09075150fda0c306dbf990b599770d6ef22512168a6abb2f36f3627ebe1428399f90b04a31c4bd19c6f43f6dc2d4fd7580bd2abe669fe0c

test:
  secret_key_base: 9e4b81fe0b243b7b03fe9e6a12d8998392ebc7499a539b627ce35a0aacd16ba0af72971be6b829ae7ba262381538a407f7819cb31a32d587178e8df072d15777

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
